services:
  web:
    image: nginx
    container_name: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
    logging:
      driver: "json-file"
      options:
          max-size: "10M"
          max-file: "10"
